export * from './applicationController.service';
import { ApplicationControllerApi } from './applicationController.service';
export * from './applicationController.serviceInterface';
export * from './authController.service';
import { AuthControllerApi } from './authController.service';
export * from './authController.serviceInterface';
export * from './menuController.service';
import { MenuControllerApi } from './menuController.service';
export * from './menuController.serviceInterface';
export * from './privilegeController.service';
import { PrivilegeControllerApi } from './privilegeController.service';
export * from './privilegeController.serviceInterface';
export * from './roleController.service';
import { RoleControllerApi } from './roleController.service';
export * from './roleController.serviceInterface';
export * from './userController.service';
import { UserControllerApi } from './userController.service';
export * from './userController.serviceInterface';
export * from './utilsController.service';
import { UtilsControllerApi } from './utilsController.service';
export * from './utilsController.serviceInterface';
export const APIS = [ApplicationControllerApi, AuthControllerApi, MenuControllerApi, PrivilegeControllerApi, RoleControllerApi, UserControllerApi, UtilsControllerApi];
