/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApplicationRequestDTO } from '../model/models';
import { ErrorResponseDto } from '../model/models';
import { ResponseDtoApplicationResponseDTO } from '../model/models';
import { ResponseDtoListApplicationResponseDTO } from '../model/models';
import { ResponseDtoMessageResponseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ApplicationControllerApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    activate3(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     */
    getAll4(extraHttpRequestParams?: any): Observable<ResponseDtoListApplicationResponseDTO>;

    /**
     * 
     * 
     * @param id 
     */
    inactive(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     * @param applicationRequestDTO 
     */
    save3(applicationRequestDTO: ApplicationRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoApplicationResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param applicationRequestDTO 
     */
    update1(id: number, applicationRequestDTO: ApplicationRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoApplicationResponseDTO>;

}
