/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponseDto } from '../model/models';
import { LoginRequestDTO } from '../model/models';
import { PasswordChangeRequestDTO } from '../model/models';
import { ResponseDtoBoolean } from '../model/models';
import { ResponseDtoMessageResponseDTO } from '../model/models';
import { ResponseDtoTokenResponseDTO } from '../model/models';
import { ResponseDtoUserRegisterResponseDTO } from '../model/models';
import { UserRequestoDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthControllerApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param username 
     */
    generateTokenForgotPassword(username: string, extraHttpRequestParams?: any): Observable<ResponseDtoTokenResponseDTO>;

    /**
     * Login to obtain JWT token
     * 
     * @param loginRequestDTO 
     */
    login(loginRequestDTO: LoginRequestDTO, extraHttpRequestParams?: any): Observable<string>;

    /**
     * Logout the current user
     * Invalidates the user\&#39;s session or token
     */
    logout(extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param userRequestoDTO 
     */
    register(userRequestoDTO: UserRequestoDTO, extraHttpRequestParams?: any): Observable<ResponseDtoUserRegisterResponseDTO>;

    /**
     * 
     * 
     * @param token 
     * @param passwordChangeRequestDTO 
     */
    restorePassword(token: string, passwordChangeRequestDTO: PasswordChangeRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoBoolean>;

    /**
     * 
     * 
     * @param token 
     */
    validateTokenForgotPassword(token: string, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

}
