/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponseDto } from '../model/models';
import { MenuRequestDTO } from '../model/models';
import { ResponseDtoListMenuResponseDTO } from '../model/models';
import { ResponseDtoMenuResponseDTO } from '../model/models';
import { ResponseDtoMessageResponseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MenuControllerApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    activate2(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteUser3(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     */
    getAll3(extraHttpRequestParams?: any): Observable<ResponseDtoListMenuResponseDTO>;

    /**
     * 
     * 
     * @param menuRequestDTO 
     */
    save2(menuRequestDTO: MenuRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoMenuResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param menuRequestDTO 
     */
    update(id: number, menuRequestDTO: MenuRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoMenuResponseDTO>;

}
