/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponseDto } from '../model/models';
import { PrivilegeRequestDTO } from '../model/models';
import { ResponseDtoListPrivilegeResponseDTO } from '../model/models';
import { ResponseDtoMessageResponseDTO } from '../model/models';
import { ResponseDtoPrivilegeResponseDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PrivilegeControllerApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    activate1(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteUser2(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     */
    getAll2(extraHttpRequestParams?: any): Observable<ResponseDtoListPrivilegeResponseDTO>;

    /**
     * 
     * 
     * @param privilegeRequestDTO 
     */
    save1(privilegeRequestDTO: PrivilegeRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoPrivilegeResponseDTO>;

}
