/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponseDto } from '../model/models';
import { ResponseDtoListRolesResponseDTO } from '../model/models';
import { ResponseDtoMessageResponseDTO } from '../model/models';
import { ResponseDtoRoleDetailsResponseDTO } from '../model/models';
import { ResponseDtoRolesResponseDTO } from '../model/models';
import { RoleRequestDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoleControllerApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    activate(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param roleRequestDTO 
     */
    addMenus(id: number, roleRequestDTO: RoleRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoRolesResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param roleRequestDTO 
     */
    addPrivileges(id: number, roleRequestDTO: RoleRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoRolesResponseDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteUser1(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     */
    getAll1(extraHttpRequestParams?: any): Observable<ResponseDtoListRolesResponseDTO>;

    /**
     * 
     * 
     * @param id 
     */
    getById1(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoRoleDetailsResponseDTO>;

    /**
     * 
     * 
     * @param roleRequestDTO 
     */
    save(roleRequestDTO: RoleRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoRolesResponseDTO>;

}
