/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ErrorResponseDto } from '../model/models';
import { PasswordChangeRequestDTO } from '../model/models';
import { ResponseDtoListUserResponseDTO } from '../model/models';
import { ResponseDtoMessageResponseDTO } from '../model/models';
import { ResponseDtoUserDetailsResponseDTO } from '../model/models';
import { ResponseDtoUserResponseDTO } from '../model/models';
import { UserRequestoDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserControllerApiInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    activateUser(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param passwordChangeRequestDTO 
     */
    changePassword(id: number, passwordChangeRequestDTO: PasswordChangeRequestDTO, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteUser(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     */
    getAll(extraHttpRequestParams?: any): Observable<ResponseDtoListUserResponseDTO>;

    /**
     * 
     * 
     * @param id 
     */
    getById(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoUserDetailsResponseDTO>;

    /**
     * 
     * 
     * @param id 
     */
    suspendUser(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     * @param id 
     */
    unsuspendUser(id: number, extraHttpRequestParams?: any): Observable<ResponseDtoMessageResponseDTO>;

    /**
     * 
     * 
     * @param id 
     * @param userRequestoDTO 
     */
    updateUser(id: number, userRequestoDTO: UserRequestoDTO, extraHttpRequestParams?: any): Observable<ResponseDtoUserResponseDTO>;

}
