server {
    listen 80;
    server_name app.inventory.integritysolutions.com.ec;

    root /usr/share/nginx/html;   # o la ruta donde esté tu frontend estático
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}