/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationResponseDTO { 
    id?: number;
    name?: string;
    image?: string;
    callback?: string;
    description?: string;
    active?: boolean;
    creationDate?: string;
    lastModificationDate?: string;
    gitlabRepositoryId?: number;
    currentVersion?: string;
    visible?: boolean;
    projectId?: number;
}

