/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationRequestDTO { 
    name: string;
    callback: string;
    description: string;
    gitlabRepositoryId?: number;
    currentVersion?: string;
    projectId?: number;
}

