/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MenuRequestDTO { 
    label: string;
    description?: string;
    route: string;
    parentId?: number;
    icon?: string;
    order: number;
    internalRoute: boolean;
    applicationId: number;
}

