/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MenuResponseDTO } from './menuResponseDTO';
import { MetadataResponseDto } from './metadataResponseDto';


export interface ResponseDtoListMenuResponseDTO { 
    meta?: MetadataResponseDto;
    data?: Array<MenuResponseDTO>;
}

