/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrivilegeResponseDTO } from './privilegeResponseDTO';


export interface RolesResponseDTO { 
    id: number;
    name: string;
    active: boolean;
    rolePrivileges: Set<PrivilegeResponseDTO>;
}

