/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MenuResponseDTO } from './menuResponseDTO';
import { PrivilegeResponseDTO } from './privilegeResponseDTO';


export interface RoleDetailsResponseDTO { 
    id?: number;
    nombre?: string;
    active?: boolean;
    rolePrivileges?: Set<PrivilegeResponseDTO>;
    roleMenus?: Set<MenuResponseDTO>;
}

