/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolesResponseDTO } from './rolesResponseDTO';
import { PrivilegeResponseDTO } from './privilegeResponseDTO';


export interface UserRegisterResponseDTO { 
    id?: number;
    username?: string;
    email?: string;
    firstNames?: string;
    employeeId?: number;
    active?: boolean;
    suspended?: boolean;
    roles?: Set<RolesResponseDTO>;
    privileges?: Set<PrivilegeResponseDTO>;
    password?: string;
    loggedIn?: boolean;
}

