/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

<<<<<<< HEAD

export interface UserRequestoDTO { 
    username: string;
    email: string;
    firstNames: string;
    employeeId: number;
    rolesId: Set<number>;
    privilegesId?: Set<number>;
    menusId?: Set<number>;
}

=======
export interface UserRequestoDTO {
  username: string;
  email: string;
  firstNames: string;
  employeeId: number;
  rolesId: number[];
  privilegesId?: number[];
  menusId?: number[];
}
>>>>>>> 2dafe857f2557c49466b120dd49569973c1cfb73
