/**
 * Inventory AUTH API - JWT Secured
 *
 * Contact: adrian2x2001@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MenuResponseDTO } from './menuResponseDTO';
import { PrivilegeResponseDTO } from './privilegeResponseDTO';
import { RoleDetailsResponseDTO } from './roleDetailsResponseDTO';


export interface UserDetailsResponseDTO { 
    id?: number;
    username?: string;
    email?: string;
    firstNames?: string;
    employeeId?: number;
    lastModificationDate?: string;
    lastConnection?: string;
    active?: boolean;
    suspended?: boolean;
    roles?: Set<RoleDetailsResponseDTO>;
    privileges?: Set<PrivilegeResponseDTO>;
    menus?: Set<MenuResponseDTO>;
    loggedIn?: boolean;
}

